version: '3.3'
services:
  server:
    build: ./server
    container_name: server_api_c
    ports:
      - '2000:2000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules  
    depends_on:
      - db  
    env_file:
      - ./server/.env
  react:
    build: ./react
    container_name: myreactapp_c
    ports:
      - '3000:3000'
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules  
    stdin_open: true
    tty: true
    depends_on:
      - server
    env_file:
      - ./react/.env
    command: ["npm", "run", "lint", "--quiet"]
    
  db:
    container_name: dbreact
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
  db_data: {}
